import Providers from "@/components/Layout-Comp/Providers";
import "./globals.scss";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Header from "@/components/Layout-Comp/Header";
import Footer from "@/components/Layout-Comp/Footer";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kudryashka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
